import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import { COMPANY_NAME } from '@/utils/constants'
import { formatCurrency, formatMonthYear, formatDate } from '@/utils/formatters'

export function generateContributionPDF({
  month,
  year,
  summary,
  payments,
  generatedBy,
  reportTitle = 'EMPLOYEE MONTHLY CONTRIBUTION REPORT',
}) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const pageWidth = doc.internal.pageSize.getWidth()

  // Header
  doc.setFillColor(12, 142, 231)
  doc.rect(0, 0, pageWidth, 28, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text(COMPANY_NAME.toUpperCase(), 14, 13)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(reportTitle, 14, 21)

  // Period + summary box
  doc.setTextColor(30, 41, 59)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.text(`Period: ${formatMonthYear(month, year)}`, 14, 40)

  doc.setDrawColor(226, 232, 240)
  doc.setFillColor(248, 250, 252)
  doc.roundedRect(14, 46, pageWidth - 28, 32, 2, 2, 'FD')

  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  const cols = [
    ['Total Employees', String(summary.total_employees ?? 0)],
    ['Active Employees', String(summary.active_employees ?? 0)],
    ['Paid', String(summary.paid_count ?? 0)],
    ['Unpaid', String(summary.unpaid_count ?? 0)],
    ['Partial', String(summary.partial_count ?? 0)],
    ['Expected', formatCurrency(summary.expected_amount)],
    ['Collected', formatCurrency(summary.collected_amount)],
    ['Remaining', formatCurrency(summary.remaining_amount)],
  ]

  const colWidth = (pageWidth - 28) / 4
  cols.forEach((c, i) => {
    const col = i % 4
    const row = Math.floor(i / 4)
    const x = 18 + col * colWidth
    const y = 54 + row * 10
    doc.setTextColor(100, 116, 139)
    doc.text(c[0], x, y)
    doc.setTextColor(15, 23, 42)
    doc.setFont('helvetica', 'bold')
    doc.text(c[1], x, y + 4.5)
    doc.setFont('helvetica', 'normal')
  })

  // Table
  const rows = payments.map((p) => [
    p.employees?.employee_code || '—',
    p.employees?.full_name || '—',
    formatCurrency(p.amount),
    p.status,
    formatDate(p.payment_date),
  ])

  autoTable(doc, {
    startY: 86,
    head: [['Employee ID', 'Employee Name', 'Amount', 'Status', 'Payment Date']],
    body: rows,
    theme: 'grid',
    styles: { fontSize: 9, cellPadding: 3, textColor: [30, 41, 59] },
    headStyles: { fillColor: [12, 142, 231], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    columnStyles: {
      0: { cellWidth: 30 },
      1: { cellWidth: 65 },
      2: { cellWidth: 25, halign: 'right' },
      3: { cellWidth: 25, halign: 'center' },
      4: { cellWidth: 30, halign: 'center' },
    },
  })

  // Footer
  const finalY = doc.lastAutoTable.finalY + 12
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(15, 23, 42)
  doc.text(`Total Collected: ${formatCurrency(summary.collected_amount)}`, 14, finalY)

  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(100, 116, 139)
  doc.text(`Generated by: ${generatedBy || 'System'}`, 14, finalY + 8)
  doc.text(`Generated Date: ${formatDate(new Date())}`, 14, finalY + 13)

  // Page numbers
  const pageCount = doc.internal.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(148, 163, 184)
    doc.text(
      `Page ${i} of ${pageCount}`,
      pageWidth - 14,
      doc.internal.pageSize.getHeight() - 8,
      { align: 'right' }
    )
  }

  return doc
}

export function downloadPDF(doc, filename) {
  doc.save(filename)
}